### PR TITLE
Using cassettes instead of mocking

### PR DESCRIPTION
**Pull request by bbelderbos**
Did have to update the tests - please double-check ...
Also added requirements, GH Actions, test package file.

### CODE REVIEW

**Review by pedrojunqueira — CHANGES_REQUESTED** [review]
Hi @bbelderbos almost all good. Just thinking if adding __init__.py to tests folder can be avoidable. On the setup.py i configured to look for packages without specifying where on installation. Should change that there? Is Python going to recognise tests as a package then? Other than that it is good to go.

**Comment by bbelderbos** [comment]
Good point it does running `python setup.py sdist --formats=gztar,zip`, so I just excluded them: https://github.com/pedrojunqueira/job-seeker/pull/1/commits/75eba03dffd905e9ba5f154531bfcb33081ff843 - btw are you planning to drop `setup.py` and use `pyproject.toml` for this?

**Comment by pedrojunqueira** [comment]
> Good point it does running `python setup.py sdist --formats=gztar,zip`, so I just excluded them: [75eba03](https://github.com/pedrojunqueira/job-seeker/commit/75eba03dffd905e9ba5f154531bfcb33081ff843) - btw are you planning to drop `setup.py` and use `pyproject.toml` for this?

I was not planning to drop `setup.py`. I just follow the docs guide.  Keep like this for now.

**Review by pedrojunqueira — APPROVED** [review]
It is good to go now. I will merge.

**Comment by pedrojunqueira** [comment]
adding CI and improving test mock of requests with cassette.

**Pull request merged**
